server:
  port: 8090
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=GMT
    username: root
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 1000
    max-wait: 10000
    min-idle: 100
    initial-size: 100


  jpa:
    hibernate:
      ddl-auto: update

mybatis:
  type-aliases-package: com.lpy.springboot.model
  mapper-locations: classpath:mapping/*.xml



